import { useEffect, useState } from "react";
import { Alert, FlatList, Modal, Pressable, SafeAreaView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import RazorpayCheckout from "react-native-razorpay";
import { api } from "@/src/api";
import { useSession } from "@/src/session";
import { colors } from "@/src/ui";

type Astrologer = { id:string; speciality:string|null; ratePerMin:number; isOnline:boolean; isBusy:boolean; averageRating:number; reviewCount:number; user:{name:string} };
export default function HomeScreen() {
  const { user, refresh } = useSession(); const [items,setItems]=useState<Astrologer[]>([]); const [selected,setSelected]=useState<Astrologer|null>(null); const [loading,setLoading]=useState(true);
  useEffect(()=>{ api<Astrologer[]>("/api/astrologers").then(setItems).catch(()=>Alert.alert("Could not load astrologers")).finally(()=>setLoading(false)); },[]);
  const start = async (astro:Astrologer, bypass=false) => { try { const session=await api<{sessionId:string}>("/api/chat/start",{method:"POST",body:JSON.stringify({astrologerId:astro.id})}); router.push(`/chat/${session.sessionId}`); } catch(error:any) { if(error.status===402 && error.body?.introOfferAvailable && !bypass) setSelected(astro); else if(error.status===402) router.push("/(tabs)/wallet"); else Alert.alert("Could not start chat",error.message); } };
  const unlock = async () => { try { const order=await api<any>("/api/user/wallet/create-order",{method:"POST",body:JSON.stringify({amount:1,purpose:"INTRO_CHAT_PASS"})}); const result:any=await RazorpayCheckout.open({key:order.keyId,amount:order.amount*100,currency:order.currency,name:"AstroWalla",description:"3-minute Intro Chat Pass",order_id:order.orderId,theme:{color:colors.orange}}); await api("/api/user/wallet/verify",{method:"POST",body:JSON.stringify({...result})}); const astro=selected; setSelected(null); await refresh(); if(astro) start(astro,true); } catch(error:any) { if(error?.code!==0) Alert.alert("Payment could not be completed",error?.message||"Try again"); } };
  return <SafeAreaView style={styles.screen}><View style={styles.header}><View><Text style={styles.greeting}>Hello, {user?.name?.split(" ")[0] || "Seeker"}</Text><Text style={styles.caption}>Find your guide for today</Text></View><Pressable style={styles.wallet} onPress={()=>router.push("/(tabs)/wallet")}><Text style={styles.walletText}>Rs {user?.walletBalance?.toFixed(0) || 0}</Text><Text style={styles.plus}>+</Text></Pressable></View>
  <FlatList data={items} refreshing={loading} onRefresh={()=>api<Astrologer[]>("/api/astrologers").then(setItems)} keyExtractor={x=>x.id} contentContainerStyle={styles.list} ListHeaderComponent={<Text style={styles.section}>Available astrologers</Text>} renderItem={({item})=><View style={styles.card}><View style={styles.avatar}><Text style={styles.avatarText}>{item.user.name[0]}</Text></View><View style={styles.info}><Text style={styles.name}>{item.user.name}</Text><Text style={styles.speciality}>{item.speciality || "Vedic Astrology"}</Text><Text style={styles.meta}>{item.averageRating ? `${item.averageRating.toFixed(1)} rating` : "New guide"}  ·  Rs {item.ratePerMin}/min</Text></View><Pressable disabled={!item.isOnline||item.isBusy} onPress={()=>start(item)} style={[styles.chatButton,(!item.isOnline||item.isBusy)&&styles.disabled]}><Text style={styles.chatText}>{item.isBusy?"Busy":item.isOnline?"Chat":"Offline"}</Text></Pressable></View>} />
  <Modal visible={!!selected} transparent animationType="slide" onRequestClose={()=>setSelected(null)}><View style={styles.overlay}><View style={styles.paywall}><View style={styles.offerIcon}><Text style={styles.offerNumber}>1</Text></View><Text style={styles.offerTitle}>Start with 3 minutes</Text><Text style={styles.offerBody}>Unlock your first three minutes of chat for just Rs 1.</Text><Pressable style={styles.primary} onPress={unlock}><Text style={styles.primaryText}>Pay Rs 1 and unlock</Text></Pressable><Pressable onPress={()=>setSelected(null)}><Text style={styles.dismiss}>Not now</Text></Pressable></View></View></Modal>
  </SafeAreaView>;
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:colors.cream},header:{padding:20,flexDirection:"row",justifyContent:"space-between",alignItems:"center",backgroundColor:"white",borderBottomWidth:1,borderColor:colors.border},greeting:{fontSize:22,fontWeight:"800",color:colors.ink},caption:{color:colors.muted,marginTop:3},wallet:{flexDirection:"row",gap:8,alignItems:"center",borderWidth:1.5,borderColor:"#91DAB8",paddingVertical:9,paddingLeft:12,paddingRight:8,borderRadius:22},walletText:{fontWeight:"800",color:colors.green},plus:{backgroundColor:colors.green,color:"white",width:19,height:19,textAlign:"center",borderRadius:10,fontWeight:"800"},list:{padding:16,gap:12},section:{fontSize:17,fontWeight:"800",color:colors.ink,marginBottom:5},card:{backgroundColor:"white",borderRadius:16,padding:14,flexDirection:"row",alignItems:"center",gap:12,borderWidth:1,borderColor:colors.border},avatar:{width:48,height:48,borderRadius:24,backgroundColor:"#FFF0E5",borderWidth:2,borderColor:colors.orange,alignItems:"center",justifyContent:"center"},avatarText:{fontWeight:"800",color:colors.orange,fontSize:19},info:{flex:1},name:{fontWeight:"800",fontSize:16,color:colors.ink},speciality:{fontSize:13,color:colors.orange,marginTop:2},meta:{fontSize:12,color:colors.muted,marginTop:5},chatButton:{backgroundColor:colors.orange,borderRadius:10,paddingHorizontal:13,paddingVertical:10},disabled:{backgroundColor:"#CDD2D9"},chatText:{color:"white",fontWeight:"800",fontSize:12},overlay:{flex:1,backgroundColor:"rgba(31,41,55,.45)",justifyContent:"flex-end",padding:16},paywall:{backgroundColor:"white",borderRadius:22,padding:24,alignItems:"center",gap:12},offerIcon:{width:54,height:54,borderRadius:17,backgroundColor:"#FDE6B4",alignItems:"center",justifyContent:"center"},offerNumber:{fontSize:25,fontWeight:"900",color:colors.orangeDark},offerTitle:{fontSize:23,fontWeight:"800",color:colors.ink},offerBody:{textAlign:"center",lineHeight:21,color:colors.muted},primary:{backgroundColor:colors.orange,borderRadius:13,padding:16,alignSelf:"stretch",alignItems:"center",marginTop:8},primaryText:{color:"white",fontWeight:"800",fontSize:15},dismiss:{color:colors.muted,fontWeight:"700",padding:8} });
