import { useEffect, useRef, useState } from "react";
import { ActivityIndicator, FlatList, KeyboardAvoidingView, Platform, Pressable, SafeAreaView, StyleSheet, Text, TextInput, View } from "react-native";
import { useLocalSearchParams, router } from "expo-router";
import { io, Socket } from "socket.io-client";
import { api } from "@/src/api";
import { useSession } from "@/src/session";
import { colors } from "@/src/ui";

type Message={id:string;senderId:string;content:string;createdAt:string};
type ChatSession={id:string;status:string;messages:Message[];astrologer:{id:string;user:{name:string};ratePerMin:number};user:{walletBalance:number}};
export default function ChatScreen(){const {sessionId}=useLocalSearchParams<{sessionId:string}>();const {user,refresh}=useSession();const [chat,setChat]=useState<ChatSession|null>(null);const [text,setText]=useState("");const [typing,setTyping]=useState(false);const [ended,setEnded]=useState(false);const [connected,setConnected]=useState(false);const socket=useRef<Socket|null>(null);const list=useRef<FlatList<Message>>(null);
useEffect(()=>{let active=true;(async()=>{try{const [session,token]=await Promise.all([api<ChatSession>(`/api/chat/session/${sessionId}`),api<{token:string}>("/api/chat/socket-token")]);if(!active)return;setChat(session);setEnded(session.status==="ENDED");const client=io(process.env.EXPO_PUBLIC_SOCKET_URL||"http://10.0.2.2:3001",{auth:{token:token.token},transports:["websocket"]});socket.current=client;client.on("connect",()=>{setConnected(true);client.emit("join_session",{sessionId})});client.on("disconnect",()=>setConnected(false));client.on("receive_message",(message:Message)=>setChat(current=>current?{...current,messages:[...current.messages,message]}:current));client.on("user_typing",({isTyping}:{isTyping:boolean})=>setTyping(isTyping));client.on("session_ended",()=>{setEnded(true);refresh()});}catch{router.back()}})();return()=>{active=false;socket.current?.disconnect()}},[sessionId,refresh]);
const send=()=>{if(!text.trim())return;socket.current?.emit("send_message",{sessionId,content:text.trim()});socket.current?.emit("typing",{sessionId,isTyping:false});setText("")};const end=()=>socket.current?.emit("end_session",{sessionId});
if(!chat)return <SafeAreaView style={styles.loading}><ActivityIndicator color={colors.orange}/></SafeAreaView>;const name=chat.astrologer.user.name;return <SafeAreaView style={styles.screen}><View style={styles.header}><Pressable onPress={()=>router.back()} style={styles.back}><Text style={styles.backText}>‹</Text></Pressable><View style={styles.avatar}><Text style={styles.avatarText}>{name[0]}</Text></View><View style={styles.headerInfo}><Text style={styles.name}>{name}</Text><Text style={styles.status}>{typing?"Typing...":connected?"Online":"Connecting..."}</Text></View><Pressable style={styles.wallet} onPress={()=>router.push("/(tabs)/wallet")}><Text style={styles.walletText}>Rs {user?.walletBalance?.toFixed(0)||0}</Text><Text style={styles.plus}>+</Text></Pressable>{!ended&&<Pressable onPress={end} style={styles.end}><Text style={styles.endText}>End</Text></Pressable>}</View>
<KeyboardAvoidingView style={styles.flex} behavior={Platform.OS==="ios"?"padding":undefined}><FlatList ref={list} data={chat.messages} keyExtractor={item=>item.id} onContentSizeChange={()=>list.current?.scrollToEnd({animated:true})} contentContainerStyle={styles.messages} ListHeaderComponent={<View style={styles.today}><Text style={styles.todayText}>Today</Text></View>} renderItem={({item})=>{const mine=item.senderId===user?.id;return <View style={[styles.messageRow,mine?styles.mine:styles.theirs]}><View style={[styles.bubble,mine?styles.mineBubble:styles.theirBubble]}><Text style={[styles.messageText,mine&&styles.mineText]}>{item.content}</Text></View><Text style={styles.time}>{new Date(item.createdAt).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</Text></View>}} ListFooterComponent={typing?<Text style={styles.typing}>{name} is typing...</Text>:null}/>{ended?<View style={styles.ended}><Text style={styles.endedTitle}>Session ended</Text><Text style={styles.endedText}>Your wallet is ready whenever you want to continue.</Text><Pressable style={styles.continue} onPress={()=>router.push("/(tabs)/wallet")}><Text style={styles.continueText}>Add balance</Text></Pressable></View>:<View style={styles.composer}><TextInput value={text} onChangeText={value=>{setText(value);socket.current?.emit("typing",{sessionId,isTyping:!!value})}} placeholder="Type your message..." style={styles.input} multiline onSubmitEditing={send}/><Pressable onPress={send} disabled={!text.trim()} style={[styles.send,!text.trim()&&styles.sendDisabled]}><Text style={styles.sendText}>↑</Text></Pressable></View>}</KeyboardAvoidingView></SafeAreaView>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:colors.cream},flex:{flex:1},loading:{flex:1,justifyContent:"center",alignItems:"center",backgroundColor:colors.cream},header:{backgroundColor:"white",borderBottomWidth:1,borderColor:colors.border,padding:12,flexDirection:"row",alignItems:"center",gap:8},back:{width:38,height:38,borderRadius:19,borderWidth:2,borderColor:colors.orange,alignItems:"center",justifyContent:"center"},backText:{fontSize:31,lineHeight:32,color:colors.orange},avatar:{height:42,width:42,borderRadius:21,backgroundColor:"#FFF0E5",borderWidth:2,borderColor:colors.orange,alignItems:"center",justifyContent:"center"},avatarText:{color:colors.orange,fontWeight:"900"},headerInfo:{flex:1},name:{fontSize:16,fontWeight:"800",color:colors.ink},status:{fontSize:13,color:colors.orange,marginTop:2},wallet:{borderWidth:1.5,borderColor:"#91DAB8",paddingVertical:7,paddingLeft:9,paddingRight:6,borderRadius:20,flexDirection:"row",gap:6,alignItems:"center"},walletText:{color:colors.green,fontSize:12,fontWeight:"800"},plus:{color:"white",backgroundColor:colors.green,width:17,height:17,borderRadius:9,textAlign:"center",fontWeight:"900"},end:{paddingHorizontal:9,paddingVertical:7,borderRadius:18,backgroundColor:"#FFF0F0"},endText:{color:colors.red,fontWeight:"800",fontSize:12},messages:{padding:16,gap:7},today:{alignItems:"center",paddingVertical:8},todayText:{backgroundColor:colors.ink,color:"white",paddingHorizontal:16,paddingVertical:7,borderRadius:18,fontWeight:"800",fontSize:12},messageRow:{maxWidth:"82%",marginTop:4},mine:{alignSelf:"flex-end",alignItems:"flex-end"},theirs:{alignSelf:"flex-start",alignItems:"flex-start"},bubble:{paddingHorizontal:14,paddingVertical:11,borderRadius:16},mineBubble:{backgroundColor:colors.orange,borderBottomRightRadius:4},theirBubble:{backgroundColor:"white",borderBottomLeftRadius:4},messageText:{fontSize:15,color:colors.ink,lineHeight:21},mineText:{color:"white"},time:{fontSize:11,color:colors.muted,marginTop:3},typing:{color:colors.muted,fontStyle:"italic",textAlign:"center",paddingVertical:10},composer:{flexDirection:"row",gap:10,alignItems:"flex-end",padding:12,backgroundColor:"white",borderTopWidth:1,borderColor:colors.border},input:{flex:1,borderWidth:1,borderColor:"#D9DDE1",borderRadius:25,paddingHorizontal:17,paddingVertical:12,fontSize:16,maxHeight:110},send:{width:50,height:50,borderRadius:25,alignItems:"center",justifyContent:"center",backgroundColor:colors.orange},sendDisabled:{backgroundColor:"#D9DDE1"},sendText:{color:"white",fontSize:25,fontWeight:"800"},ended:{margin:16,backgroundColor:"white",borderRadius:18,padding:20,alignItems:"center",gap:8},endedTitle:{fontWeight:"900",fontSize:18,color:colors.ink},endedText:{color:colors.muted,textAlign:"center"},continue:{backgroundColor:colors.orange,borderRadius:12,paddingHorizontal:18,paddingVertical:12,marginTop:6},continueText:{color:"white",fontWeight:"800"}});
